spring.config.import=optional:file:.env[.properties]
spring.application.name=MiniProject

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT ?? - env???? ????
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}
jwt.access-token-expire-in=${JWT_ACCESS_TOKEN_EXPIRE}
jwt.refresh-token-expire-in=${JWT_REFRESH_TOKEN_EXPIRE}
jwt.prefix = ${JWT_PREFIX:Bearer}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# UserDetailsService ?? ?? ????
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Swagger UI ?? ??
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html