spring.application.name=MiniProject

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT ?? - env???? ????
jwt.salt=${JWT_SALT}
jwt.issuer=${JWT_ISSUER}
jwt.access-token-expire-in=${JWT_ACCESS_TOKEN_EXPIRE}
jwt.refresh-token-expire-in=${JWT_REFRESH_TOKEN_EXPIRE}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI ?? ??
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html